### ISSUE TITLE
Add ability to use `useTooltipTrigger` with buttons

### ISSUE THREAD

**Issue by maksimsemenov** [adobe/react-spectrum#1689]
# 🙋 Feature Request
Right now, as I understood from the source code, there is no way to use `useTooltipTrigger` with buttons with assigned actions. `useTooltipTrigger` defines its own button press events. So if the button has its own press handler, it will not work with the tooltip.

## 🤔 Expected Behavior
It should be possible to use tooltip with the button and assign custom press handlers to that button as well.

## 💁 Possible Solution
Allow `useTooltipTrigger` trigger to accept press handlers (`onClick`, etc`) and pass merge them with its own.

As an alternative, it can be built-into `mergeProps` utility, so it will wrap function properties with the same name, into one. But this seems like a much bigger change.

**Comment by devongovett** [comment]
I'm not sure I understand the issue. We use tooltip trigger with buttons in React Spectrum. Does it work to use `mergeProps` to combine the props from `useButton` and `useTooltipTrigger`?

**Comment by so99ynoodles** [comment]
@maksimsemenov 
Here's a codesandbox example. 
It should work fine.
https://codesandbox.io/s/react-spectrum-usetooltiptrigger-qinxr

@devongovett 
I found an issue from the example above that hovering a button does not trigger the `open()`,
 figured out that it was because `currentModality` was null by default.
To fix it, I needed to call `useInteractionModality` by myself (please look at L42).
I think `useTooltipTrigger` or `useFocusable` needs to call `useInteractionModality` inside of it to solve the issue?

**Comment by devongovett** [comment]
Yeah that issue should already be fixed by a recent PR which will go out in the next release.

**Comment by maksimsemenov** [comment]
Hmm, yeah, it seems to work correctly. Even if I don't use `useButton` hook. There probably was something wrong with my setup, or the way I was using it. Thanks for looking into this.

**Comment by maksimsemenov** [comment]
Hmm, so I did a little bit of testing, and it looks very weird. I created a new [repo with the example from the codesandbox](https://github.com/maksimsemenov/react-aria-tooltip). And it just doesn't work. I tried both `useFocusVisible` and `useInteractionModality` and it does not fix it.

So not sure, if I need to create a separate issue, or just leave a reproduction example here or maybe add it to #1175

**Comment by snowystinger** [comment]
I think you forgot useButton on your button? let me know if that fixes it.

**Comment by maksimsemenov** [comment]
I think my main issue is that it does not even show a tooltip. And the code is identical to [official docs](https://react-spectrum.adobe.com/react-aria/useTooltipTrigger.html). Or am I missing something?

**Comment by snowystinger** [comment]
I just ran yours, in the console there is a warning about a misspelled `clasName` if you change it to `className` it works

**Comment by maksimsemenov** [comment]
Oh, my gosh 🤦‍♂️. Thanks, and sorry for bombarding you with this...
