### ISSUE TITLE
Issues with modal scrolling + focus on Safari

### ISSUE THREAD

**Issue by jeffijoe** [adobe/react-spectrum#7902]
### Provide a general summary of the issue here

Forms in modal dialogs on iOS Safari continue to be a source of great pain. 😅 

### 🤔 Expected Behavior?

When focusing inputs, the dialog should be scrolled to center the input, and the modal overlay should be positioned correctly.

### 😯 Current Behavior

When focusing inputs, the focus jumps immediately, and the input being focused is not being centered; rather, it seems to scroll to the point where the top of the input is at the top of the dialog scroll container. Additionally, focusing inputs further down in the dialog seems to shift the modal overlay:

<img width="377" alt="Image" src="https://github.com/user-attachments/assets/8a6d1a6c-f099-4d87-9b12-74e12b91eed3" />

See the attached video, this was done on the official React Aria site.

https://github.com/user-attachments/assets/8b4e6034-12a0-4af3-823f-7dbda6eadaf9

### 🔦 Context

These issues make forms in dialogs a terrible experience for mobile Safari users.

### 🖥️ Steps to Reproduce

On the React Aria homepage, the `+` icon opens a dialog with a form. Tap on various fields to move the form around.

### Version

Latest as running on the official site

### What browsers are you seeing the problem on?

Safari

### What operating system are you using?

iOS

**Comment by snowystinger** [comment]
Thanks for reporting. I didn't recall it being quite this bad, @devongovett it looks like some of the odd restore focus behaviour is coming from our change to Popovers. Focus is forced back to the textfield and causes a jump of the page with the keyboard. However, looking back even more, focus keeps going there even before that change, it just doesn't cause the keyboard to appear for some reason.
Looks like it mainly changed in [refactor: No longer preventDefault in usePress and allow browser to manage focus (](https://github.com/adobe/react-spectrum/commit/cdba748760b1e30fb15414e8b585d05fd167819e)

Specifically, steps to repeat the behaviour I'm referring to
- Go to React Aria home page example.
- Open Add Plant dialog.
- Tap into Scientific Name. 
- Tap Sunlight. 
- Select an option.

Observed behaviour:
Focus is returned to Scientific Name at the end and the keyboard is brought up again

Previous behavior:
Focus remained on Select

**Comment by devongovett** [comment]
I think that is a separate issue. The original issue looks about the same to me in an older version: https://reactspectrum.blob.core.windows.net/reactspectrum/c53ab48ec88b85680037825da99db7a650939bf2/verdaccio/docs/react-aria/index.html

**Comment by jeffijoe** [comment]
I tested this on the latest Safari for iOS beta this morning and the overscroll issue seems to be fixed there, but the input focus behavior is still really bad - scrolling is instant (not smooth like iOS does natively) and it seems to snap it to the top makes it a less than ideal user experience.

**Comment by Eldraed** [comment]
Hello @snowystinger, I'm also interested in that issue with `input` focus that scrolls and snaps to the top of the modal and hides the label (as we can see in the video of this issue).
I tried to understand the code of `usePreventScroll` and did some testing. We have duplicated the code of `usePreventScroll` on our side for a while—it's not ideal, we know (I have in mind the `preventScrollCount`), but iOS bugs are not easy, so we try to find a balance 😅

After playing a bit with the issue, I was wondering if there is any specific reason (browser compatibility or something else) to create your own `scrollIntoView` ?
https://github.com/adobe/react-spectrum/blob/a7b1a28e0ed7b999c6cb40d7d49136ecaf2b3aed/packages/%40react-aria/overlays/src/usePreventScroll.ts#L256-L272

I tried to replace the 2 occurrences with `target.scrollIntoView({ block: 'center', behavior: 'smooth' }` and it works fine (`options` argument seems to be [well supported](https://caniuse.com/mdn-api_element_scrollintoview_options_parameter)).
It solves the issue with the label being hidden.

```diff
@@ -16,12 +16,18 @@
             // If the keyboard is already visible, do this after one additional frame
             // to wait for the transform to be removed.
             requestAnimationFrame(() => {
-              scrollIntoView(target);
+              target.scrollIntoView({
+                block: 'center',
+                behavior: 'smooth',
+              });
             });
           } else {
             // Otherwise, wait for the visual viewport to resize before scrolling so we can
             // measure the correct position to scroll to.
-            visualViewport.addEventListener('resize', () => scrollIntoView(target), {once: true});
+            visualViewport.addEventListener('resize', () => target.scrollIntoView({
+              block: 'center',
+              behavior: 'smooth',
+            }), {once: true});
           }
         }
       });
```

The only issue is that when closing the keyboard by pressing "Done", it scrolls again to the input because there is a new `focus` event on the same input 😕

To be honest, I don't know enough about all the iOS behaviors with virtual keyboard/scroll/modals etc. I made an assumption that:
- If focus happens twice on the same element, it's that the keyboard closed. And anyway, if we focus again the same element, the style should be already applied, right ?

So I made this change:
```diff
@@ -1,9 +1,16 @@
+
+let previousFocusForScroll: EventTarget | null = null;
+// ...
+
 function preventScrollMobileSafari() {
   // ...

   let onFocus = (e: FocusEvent) => {
     let target = e.target as HTMLElement;
-    if (willOpenKeyboard(target)) {
+
+    if (previousFocusForScroll !== e.target) previousFocusForScroll = null;
+
+    if (willOpenKeyboard(target) && previousFocusForScroll !== e.target) {
       setupStyles();

       // Apply a transform to trick Safari into thinking the input is at the top of the page
@@ -19,12 +26,30 @@
             // If the keyboard is already visible, do this after one additional frame
             // to wait for the transform to be removed.
             requestAnimationFrame(() => {
-              scrollIntoView(target);
+              if (previousFocusForScroll === e.target) return;
+
+              target.scrollIntoView({
+                block: 'center',
+                behavior: 'smooth',
+              });
+              previousFocusForScroll = e.target;
             });
           } else {
             // Otherwise, wait for the visual viewport to resize before scrolling so we can
             // measure the correct position to scroll to.
-            visualViewport.addEventListener('resize', () => scrollIntoView(target), {once: true});
+            visualViewport.addEventListener(
+              'resize',
+              () => {
+                if (previousFocusForScroll === e.target) return;
+
+                target.scrollIntoView({
+                  block: 'center',
+                  behavior: 'smooth',
+                });
+                previousFocusForScroll = e.target;
+              },
+              { once: true },
+            );
           }
         }
       });
```

Let's be honest, I don't have all the context/behaviors and solution is a bit raw, but it seems to work well enough.

https://github.com/user-attachments/assets/202fbbfa-833c-4048-b532-45fd3390c03b

- When input is focused => scroll to the target centered with keyboard opened
- When we select another input => scroll to the target centered
- When we close the keyboard => No scroll change (if we are near the end of the modal, of course it will go down on keyboard closing due to the change to the `visualVIewport.height` that I applied [from there](https://github.com/adobe/react-spectrum/issues/5926#issuecomment-2257306911)

Do you have any idea if this could be a good solution to integrate into react-aria `usePreventScroll` ? Or do you maybe have a better idea, or maybe have reservations (blockers) about this approach ?

Thanks !

**Comment by jeffijoe** [comment]
@Eldraed for the `scrollIntoView`, I recall reading something about it being related to making it only scroll the immediate scroll port, whereas the native `element.scrollIntoView` will force-scroll _all_ ancestor scroll ports. However, it seems to work as intended in your video, so perhaps it would be possible to fall back to the native function for this particular case?

**Comment by Eldraed** [comment]
@jeffijoe Well, I haven't checked that the parent isn't scrolled as I tested this behavior in a story made for that and there were no scroll on the body.
If that's the reason why, then, we can at least still improve the `scrollIntoView` custom method to scroll in the middle of the scroll zone. Since we apply a `useViewportSize().height` to the `position: fixed`, we will see at least the `label`.
No `smooth` but at least centered in the modal.

Too much magic in this `usePreventScroll` 😅 Hard to be fully aware of everything !

Edit: I made some test with some content in the body, it doesn't seems to scroll the body content, but maybe storybook isn't the best place to reproduce an edge case like that ? Or maybe it has been solved by Safari ?

https://github.com/user-attachments/assets/8eeb8ae0-1ecd-4969-bc65-f99b8d1642e8

**Comment by nicmeriano** [comment]
I was also facing the same issue but it turns out for my particular case locking the scroll on the `body` rather than the root `html` element solved the overlay shifting.

While this doesn't fix the jarring scroll jump, it solved the core issue that made the UI unusable in webkit mobile browsers:

```tsx
// Modal.tsx 

useLayoutEffect(() => {
  if (isIOS()) {
    document.documentElement.classList.add('ios');
  }

  return () => {
    document.documentElement.classList.remove('ios');
  };
}, []);
```

```css
// global css

html.ios[style*="overflow: hidden"] body {
  overflow: hidden;
}
```

**Comment by eranimo** [comment]
This appears to be happening in Firefox as well

**Comment by jeffijoe** [comment]
@snowystinger sorry for the ping, but does the info @Eldraed posted help with figuring this one out?

Every new React Aria release that drops, I always check whether this issue has been resolved by whatever other fixes are shipped, but no luck yet 😅

**Comment by devongovett** [comment]
@jeffijoe try out the build links on #8888 (oooh cool PR number 😄) and see if it feels better to you!

**Comment by jeffijoe** [comment]
Thanks again @devongovett ! When will the next release drop that includes the updates? 👀

**Comment by devongovett** [comment]
probably next week
