### ISSUE TITLE
Parent modal overlaps nested modal

### ISSUE THREAD

**Issue by mad-dogy** [adobe/react-spectrum#8951]
### Provide a general summary of the issue here

Parent modal overlaps nested child modal on page reload when modals are rendered via routing.

### 🤔 Expected Behavior?

On page reload at a URL corresponding to a nested modal, the child modal should appear on top of the parent modal, with the correct stacking order. The topmost modal should be fully visible and interactive.

### 😯 Current Behavior

This issue occurs when nested modals are conditionally rendered based on the current URL path. When a user navigates directly to, or refreshes the page on, a URL that should display a nested modal, the parent modal incorrectly appears in front of the child modal. This makes the child modal inaccessible, and the parent modal also becomes unresponsive to clicks. This stacking issue does not occur when navigating to the modals sequentially via user interaction (e.g., clicking buttons).

React router is used to display the actual use case. The problem still persists with no routing, just using 2 nested open modals.

### 🖥️ Steps to Reproduce

https://codesandbox.io/p/sandbox/react-aria-nested-modals-bug-vqqjmm

### Version

react-aria-components - 1.12.1

### What browsers are you seeing the problem on?

Chrome, Safari

### What operating system are you using?

macOS

**Comment by harmadema** [comment]
This has something to do with the ["ariaHideOutside"](https://github.com/adobe/react-spectrum/blob/main/packages/%40react-aria/overlays/src/ariaHideOutside.ts#L40).

Because you render 2 modals simultaneously they both apply the function ariaHideOutside and giving eachother the inert attribute. This prevents interaction for the element and its children. 

One workaround you can do is to give the modal that comes on top a small delay with setTimeout.

**Comment by snowystinger** [comment]
I don't think this is `ariaHideOutside`. This is about the order in which elements are added to the dom via portals which seems to happen in effect order as opposed to render order. In other words children are added first, then parents. You can see the behaviour here where the two elements are "not in the expected order" (at least as far as this conversation is concerned):
https://codesandbox.io/p/sandbox/dn6sxl?file=%2Fsrc%2FApp.js%3A12%2C1

I'm not sure there is anything we can reasonably do about it. Using a setTimeout of 0 will be enough to get them ordered in the correct way as mentioned by harmadema.

**Comment by harmadema** [comment]
@snowystinger what could be the reason that the 2 modals have both the inert attribute?

**Comment by snowystinger** [comment]
The issue was that one modal overlaps the other. That's not related to ariaHideOutside

I think you are correct though, there's a second issue, they won't just overlap in this order. The aria attributes would be applied in reverse. In addition, the FocusScope tree we track would probably also be wrong.

I think your suggestion to work around this issue is a good one for now. It'd be nice if we could make it easier, but will need to sit on it more, I don't have a better idea yet.

**Comment by harmadema** [comment]
@snowystinger I created a sandbox for the second issue: https://codesandbox.io/p/devbox/react-aria-nested-modals-bug-forked-n8ljnw?workspaceId=ws_WpBv21mUm1gt6JbHJWKbts

Just click "Open modal" this will open 2 modals that disables eachother. I would like to see that the last one is editable.

Should I make another issue for this second issue?

**Comment by harmadema** [comment]
@mad-dogy If you take the second inner dialog outside of its outer dialog component like so: https://codesandbox.io/p/devbox/react-aria-nested-modals-bug-forked-hgnf3m?workspaceId=ws_WpBv21mUm1gt6JbHJWKbts

<img width="1075" height="277" alt="Image" src="https://github.com/user-attachments/assets/b5da5b1b-d34b-4dce-9d20-d4c7dc773126" />

Then you dont have the stacking issue.

Only the second issue persists that the button: "Click me ({count})" isn't interactive. This is fixed in the sandbox with the delay hook.

**Comment by mad-dogy** [comment]
@harmadema , thanks. In my case it is impossible to take the second inner dialog outside of its outer dialog, and as you said, the problem with interactivity cannot not resolved here. 

All these problems are solved using settimeout. 

I solved this issue using more reliable check (with providing parent isReady flag, without using setTimeout). but it requires the modals to be nested.
https://codesandbox.io/p/sandbox/zj8w7k?file=%2Fsrc%2FApp.tsx%3A64%2C34

**Comment by snowystinger** [comment]
> Should I make another issue for this second issue?

I think it's fine to leave it in here, it's definitely related.

**Comment by tleunen** [comment]
I'm noticing a similar but different issue with modal containing an input taking focus. Let me know if you'd prefer a different issue, but I think it's pretty much the same source for all issues with nested modals. Although in my case, the modals are not opened at the same time.

For the first modal, it works fine. The second modal opened on top of the first one won't have the input auto-focused unless there's a small delay into rendering the content of that modal.

From my investigation, here's what's happening:
- Opening modal 1 moves focus to Modal 1 Input (because autofocused)
- Opening modal 2 briefly moves focus from Modal 1 input to Modal 2 input (because autofocused)
- Modal 2 input focus is lost for the close button in modal 1
- Modal 1 close button focus is lost and focus moves to Modal 2 (The dialog)

When adding a small delay to render the modal children (like skipping the first render), then it's like this:
- Opening modal 1 focus Input 1
- Opening modal 2 focus modal 2
- second delayed render makes the Input 2 taking focus because of autofocus

**Comment by AshotN** [comment]
Experiencing this issue using HeroUI drawers

```ts
function useDeferredMount(): boolean {
	const [ready, setReady] = useState(false)

	useEffect(() => {
		const id = requestAnimationFrame(() => setReady(true))
		return () => cancelAnimationFrame(id)
	}, [])

	return ready
}
```

This is what I used to defer the render for a frame. If anyone has a better solution, please share!
