### ISSUE TITLE
Focus on the first available (not disabled) option

### ISSUE THREAD

**Issue by Mariam4324** [adobe/react-spectrum#9239]
### Provide a general summary of the feature here

We would like to have the ability for the component to automatically focus the first available (non-disabled) option.

### 🤔 Expected Behavior?

When the dropdown opens, focus should move to the first active (non-disabled) option.

### 😯 Current Behavior

When the dropdown opens, the focus is set on the first option even if it is disabled.

### 💁 Possible Solution

If the current focus target cannot receive focus (e.g., the first option is disabled), the component should automatically fall back to the first available (non-disabled) option.

### 🔦 Context

This behavior causes issues with keyboard navigation and reduces accessibility. Users are forced to manually navigate through disabled items, which goes against standard UX expectations for selectable lists. Fixing this would improve predictability and usability, especially for users relying on keyboard navigation or assistive technologies.

### 💻 Examples

[_See the example_](https://codesandbox.io/p/sandbox/nice-darkness-hnkx5n)

**Comment by Mariam4324** [comment]
https://github.com/user-attachments/assets/e4084166-262e-4b73-b14b-2ab690d5e638

**Comment by snowystinger** [comment]
Looks like it's working as expected here https://codesandbox.io/p/devbox/crimson-snow-6z7zd3?workspaceId=ws_CrSP6ipvDmgFWioMsdFjKL

I'm not sure what the `onKeyDown` is for that you're passing to `useComboBox`. It's also a bit of a strange place to pass the child `Items`. My best guess is that the disabled isn't being propagated somewhere.

If you can, I recommend using the React Aria Component, it uses a new Collections implementation that isn't shown in the hooks docs yet. We're hoping to add that in the new year.

**Comment by Mariam4324** [comment]
Thanks
In your example, there is no scroll to the first active (non-disabled) option. Therefore, when opening the drop-down list, the user will think that there are no non-disabled options.
See here https://codesandbox.io/p/sandbox/quizzical-franklin-4fr6gv?file=%2Fsrc%2FApp.js%3A32%2C68
 
https://github.com/user-attachments/assets/5dfdbb7f-54f0-454b-99d1-8d9993dbf3b2

**Comment by snowystinger** [comment]
That is odd, looks like a bug.

Stepping back through and considering your specific problem, this is a combobox, it's meant to select an available option. I don't know that using disabled is the best approach here. Instead, I'd just not have that option in the set. Disabled items don't need to meet contrast, which means users may not be able to see the item anyways, so it's not helpful in telling people *what* items are disabled. Instead, if it's important, I'd consider a pattern like our ContextualHelp in React Spectrum to have a popover which tells users why certain items are disabled, what they are, and anything else that would be important. https://react-spectrum.adobe.com/react-spectrum/ContextualHelp.html#contextualhelp

**Comment by Mariam4324** [comment]
@snowystinger Thank you for the reply and for confirming that this behavior looks like a bug.

I wanted to clarify one important point regarding your suggestion.  
For our product and business scenarios it is **critically important** to show disabled options to the user. We cannot simply remove them from the collection.  

These disabled items represent existing values that are currently unavailable (for example, due to user permissions, data state, subscription plan, etc). Hiding them completely would make the interface less clear and could confuse users - they need to understand what options exist in principle, even if they cannot select them right now.

That is why we really need the combobox/listbox to automatically focus (and scroll to) the first **non-disabled** option when it opens, instead of stopping on the first disabled one.

Would it be possible to consider adding this behavior (auto-focus on first focusable item) as a feature or fix? We would really appreciate it.

Thank you!

**Comment by snowystinger** [comment]
> For our product and business scenarios it is critically important to show disabled options to the user. We cannot simply remove them from the collection.

How do you differentiate a disabled option from a non-disabled option visually? do you have a screenshot you could share?

>Would it be possible to consider adding this behavior (auto-focus on first focusable item) as a feature or fix? We would really appreciate it.

Yes, the fastest way is to submit a PR. Otherwise you will have to wait for us to prioritise it or someone else to make a PR.

**Comment by Mariam4324** [comment]
@snowystinger 

> How do you differentiate a disabled option from a non-disabled option visually? do you have a screenshot you could share?

I can’t provide a screenshot at the moment, but we always differentiate disabled options by setting their opacity to 0.5. This makes it clear to users which options are disabled.

**Comment by snowystinger** [comment]
It looks like this was fixed at some point? https://stackblitz.com/edit/adpc19dw?file=src%2FExample.tsx
I cannot reproduce it and i can't run the original codesandbox, is it still a problem?

**Comment by jsmitrah** [comment]
Yes, @snowystinger, you are totally right; it was already fixed. I couldn't reproduce it, and I am closing my PR. So we need to close the bug as fixed, right?

**Comment by snowystinger** [comment]
Closing as fixed

**Comment by Mariam4324** [comment]
Hello!

Fixed in the current version of `react-aria-components`.

**Working example:**  
https://codesandbox.io/p/sandbox/cv7gyf?file=%2Fsrc%2FApp.js

Now when the ComboBox opens, focus correctly moves to the first non-disabled option.

Thanks to @snowystinger and the team for the fix! 🙏

**Comment by Mariam4324** [comment]
https://github.com/user-attachments/assets/99ac441c-3e67-48cb-985f-8a58dc75049d

Focus on the first non-disabled item now works correctly - thank you! 👍

However, there is still one remaining issue:

**When the list is long and the first available (non-disabled) option is far down, the popover does not scroll to it.**
The virtual focus moves to the correct item, but the scroll position stays at the top. Because of this, users (especially keyboard/screen reader users) may think there are no available options.

**Expected behavior:**
When the dropdown opens, it should:
1. Focus the first non-disabled option
2. **Automatically scroll** to make that option visible

**Current behavior:**
Focus is correct, but no auto-scroll happens.

**Reproduction:**  
https://codesandbox.io/p/sandbox/cv7gyf?file=%2Fsrc%2FApp.js (many disabled items at the top)

Should I reopen the issue or is it better to create a new one specifically for the "auto-scroll to first focusable item" behavior?

Thanks again to @snowystinger and the team!

**Comment by Mariam4324** [comment]
Hi @snowystinger,
Thank you for the partial fix on focusing the first non-disabled option! 🙏
However, as I mentioned in my last comment, scrolling to the first active item is still not working. When the dropdown opens and the first few options are disabled, the list doesn't scroll to the first enabled one, which makes it look like there are no available options for keyboard/screen reader users.Could we reopen this or track the scroll part separately? Happy to provide more details or a updated repro if needed.
Thanks again!

**Comment by LFDanLu** [comment]
@Mariam4324 do you mind filing a separate issue for this actually? I had though this was the same class of issue as https://github.com/adobe/react-spectrum/issues/8703 but it still reproduces in your reproduction without strict mode so it is worth having a separate issue to track this. I'll close this one for now
